version: 2.0

id: terraform-mock-aws-provider

about:
  title: terraform-mock-aws-provider
  description: Sandbox with amazon linux OS and terraform. AWS API's are mocked with LocalStack.

contacts:
  - type: Maintainer
    name: Luis Herrera
    github: herrera-luis
    email: herrera_luis10@hotmail.com

environments:
  - type: git
    title: local
    uri: https://github.com/devops-resources/terraform-mock-aws-provider

  - type: aws
    title: dev
    uri: https://github.com/devops-resources/terraform-mock-aws-provider