version: 2.0

id: terraform-mock-aws-provider

about:
  title: terraform-mock-aws-provider
  description: Sandbox with amazon linux OS and terraform. AWS API's are mocked with LocalStack.

contacts:
  - type: Maintainer
    name: Luis Herrera
    github: herrera-luis
    email: herrera_luis10@hotmail.com

  - type: Developer
    name: Luis Herrera
    github: herrera-luis
    email: herrera_luis10@hotmail.com

environments:
  - type: git
    title: local
    uri: https://github.com/devops-resources/terraform-mock-aws-provider

  - type: aws
    title: dev
    uri: https://github.com/devops-resources/terraform-mock-aws-provider

schedule:
  launch: 2019-11-04T00:00:00.000Z
  v0.x-sunset: 2020-08-20T00:00:00.000Z

references:
  - title: Github Issue Tracker
    description: Post bug reports or feature suggestions here!
    uri: https://github.com/herrera-luis/terraform-mock-aws-provider/issues